첫번째 커밋
leekeunha/sportsMall pull request #1
Opened 2021-02-01 15:30 UTC by leekeunha

1.프로젝트 폴더 구조 형성
2.product,category,httpclient
3.유닛테스트

2021-02-01 21:14 UTC, tomlee-cmkr commented on src/app/httpClient.ts
> +        return productList.find(p => p.product_name == productName);
change the logic `p.product_name` contains `productName`

2021-02-01 21:24 UTC, tomlee-cmkr requested changes
1. create `client` folder and move client.ts into `client folder.
2. create `fixture` folder under `client` folder and move json files into `fixture` folder

2021-02-01 21:24 UTC, tomlee-cmkr commented on src/app/tests/httpClient.spec.ts
> +describe("Jasmine Test Environment", () => {
`Jasmine Test Environment` doesn't describe what is this test for.
change the description as what is the purpose of this test

2021-02-01 21:24 UTC, tomlee-cmkr commented on src/app/tests/httpClient.spec.ts
> +    it("test getProducts function", () => {
let's apply description as `it ('should ..` style
for example, it('should return a list of products JSON objects`)

ref: https://howtodoinjava.com/javascript/jasmine-unit-testing-tutorial/

2021-02-01 21:24 UTC, tomlee-cmkr commented on src/app/tests/httpClient.spec.ts
> +    });
always check at least one object to be expected. Do not only check the length of the array

2021-02-01 21:24 UTC, tomlee-cmkr commented on src/app/tests/httpClient.spec.ts
> +        expect(httpClient.getProductById(1).product_id).toBe(1);
check every property of the returned object

2021-02-02 13:20 UTC, leekeunha commented on src/app/tests/httpClient.spec.ts
> +        expect(httpClient.getProductById(1).product_id).toBe(1);
수정완료

2021-02-02 13:20 UTC, leekeunha commented on src/app/httpClient.ts
> +        return productList.find(p => p.product_name == productName);
수정완료

2021-02-02 14:49 UTC, merged